# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.6

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false

install: true

before_install:
  - git clone https://github.com/apache/incubator-openwhisk.git openwhisk
  - cd openwhisk
  - ./tools/travis/setup.sh

script:
- ../tools/travis/build.sh
